name: vhcblade_theme
description: Holds themes for VHCBlade projects.
version: 0.2.2
homepage: https://github.com/VHCBlade/vhcblade_theme

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  provider: ^6.0.5
  tuple: ^2.0.0
  
  event_bloc: ^4.2.0
  event_db: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
